### ISSUE TITLE
Please, uptodate on `autoform addon`.

### ISSUE THREAD

**Issue by thearabbit** [vazco/meteor-universe-selectize#1]
Please, uptodate on `autoform addon`.

**Comment by MichalW** [comment]
please explain - addon?

**Comment by thearabbit** [comment]
I use `vazco:universe-autoform-select` for `autoform addon` created by you.
I seem don't match up to date with this.

**Comment by thearabbit** [comment]
excuse me, if these package don't related.

**Comment by MichalW** [comment]
This package is for use **without** autoform.

in `vazco:universe-autoform-select`  we have:

```
api.use('aldeed:autoform@5.8.0');
```

**Comment by thearabbit** [comment]
So, it is the same.
But it have any bug such as:

``` js
- arrow key to select item (don't work)
```

**Comment by MichalW** [comment]
I will try to fix it soon

**Comment by thearabbit** [comment]
Thanks, I waiting ....
I found the `https://github.com/tuulbox/autoform-selectize` fork of this, and have any commit to fix:
- arrow up and down support with enter to select
- custom templates for items
  ...............

I tried to install, but don't work for `.scss` style.
