### ISSUE TITLE
Special Characters cause an exception

### ISSUE THREAD

**Issue by PAGG-ESkopal** [vazco/meteor-universe-selectize#15]
Entering a special character (like "(") causes an exception in getItemsUnselectedFiltered.

You need to escape all the RegExp special characers.  I added okSearchText and escaped all of the RegExp special characters.  Here is the corrected code:

```
UniSelectize.prototype.getItemsUnselectedFiltered = function () {
    var items = this.itemsUnselected.get();
    var searchText = this.searchText.get();
    var okSearchText = searchText;
    if (okSearchText) {
        okSearchText = searchText.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, "\\$&");
    }

    return _.filter(items, function (item) {
        if (item.label && item.label.search(new RegExp(okSearchText, 'i')) !== -1) {
            return true;
        }
        return false;
    });
};
```

**Comment by kestarumper** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
