### ISSUE TITLE
How to change selected value?

### ISSUE THREAD

**Issue by thearabbit** [vazco/meteor-universe-selectize#17]
I would like to change selected value.
```js
// options = [(select one), General, Spacial...]
formTmpl.events({
    'change [name="clientId"]'(event, instance){
        $('[name="productId"]').val('');
        // Or
        $('[name="productId"]').val('General');
    }
});
```
Please help me.

**Comment by kestarumper** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
