### ISSUE TITLE
Fixed height in CSS cuases render problem when using in Autoform in multiple mode.

### ISSUE THREAD

**Issue by luixal** [vazco/meteor-universe-selectize#18]
Hi,

I've configured a selectize input like this:

```javascript
autoform: {
  type: "universe-select",
  multiple: true,
  options: function() {
    return PlacesTypes.find().map(function(placeType, index, cursor) {
      return {
        label: placeType.type,
        value: placeType._id
      };
    });
  }
}
```

And I got it rendered inside an autoform like this:

![image](https://cloud.githubusercontent.com/assets/615268/22111604/24ee0412-de60-11e6-89ad-c9afcacde5d0.png)

If I disable the `height: 36px;` (in css' line ) or change it for a `min-height` rule it works like a charm:

![image](https://cloud.githubusercontent.com/assets/615268/22111597/20b6fa8e-de60-11e6-9b0f-1d63c2b03e70.png)

Could you change it and publish to atmosphere? would you prefer a PR?

Thanks!

PS: I know this is not the package intended to use with Autoform, I'm using a different one for that, but this rule is catching it (both packages use class `selectize`).

**Comment by kestarumper** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
