### ISSUE TITLE
How to get selected event/value?

### ISSUE THREAD

**Issue by luixal** [vazco/meteor-universe-selectize#2]
I can't get selected value, How can I get it? Any example anywhere?

A great way other packages use (like tabular, for example) is passing a config object to the template. That way, those config values are passed to the original lib.

For example:

``` html
{{> universeSelectize options=options config=config}}
```

and then, define some helpers to provide those values (items and config values):

``` javascript
Template.X.helpers({
  'options': function() {
    return Items.find();
  },
  'config': function() {
    return {
      onChange: function(value) {
        console.log('selected value: ' + value);
      }
    }
  }
})
```

Thanks!

**Comment by MichalW** [comment]
You should return array of objects in options helper:

```
'options': function() {
    return Items.find().map(function (item) {
        return {value: item._id, label: item.name};
    });
  },
```

**Comment by MichalW** [comment]
Please try this event with newest version of this package:

```
Template.X.events({
    'change select': function (e) {
        console.log('value', $(e.target).val());
    }
});
```

**Comment by luixal** [comment]
Sorry, but this doesn't work. I can get the value pro-actively, but no way of getting the event triggered.

Any solution?
