### ISSUE TITLE
Add 'required' attribute

### ISSUE THREAD

**Issue by dev5-CloudNine** [vazco/meteor-universe-selectize#22]
How do I set the required attribute to the selectize when the user needs to select at least one option?

I added a required attribute to the select element created like this:

Template.myTemplate.rendered = function ( ) {
    $('#document_type').attr('required', 'required');
}

Now, when I submit the form without selecting anything from the selectize, I get an error in the console:

An invalid form control with name='document-type' is not focusable.

**Comment by MichalW** [comment]
You should do this in your onSubmit function. You can also use Autoform + SimpleSchema to validate form.

**Comment by kestarumper** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
