### ISSUE TITLE
Resets if you leave browser and then return

### ISSUE THREAD

**Issue by nadeemja** [vazco/meteor-universe-selectize#24]
Hi,

How to create problem:

1. Chose option

2. Switch to another application than your browser (browser must be out of sight).

3. Switch back to your browser.

4. Observe that the option selected in dropdown is now reset.

Expected behaviour: Option should remain preserved.

**Comment by kestarumper** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
