### ISSUE TITLE
Clear All Selected Options via Javascript

### ISSUE THREAD

**Issue by frank1340** [vazco/meteor-universe-selectize#5]
Hello, 

How would I initiate a clear of all options in Meteor via a click?  

I suppose generally how do I access the instance so I can do something when an item is added, subtracted, and so on.

Thanks.

**Comment by MichalW** [comment]
Generally you should manipulate on **options** parameter. 

Example:

```
{{> universeSelectize name="example" options=options}}
```

in js helper:

```
options: function () {
    return Session.get('options');
}
```

and try set options via console like this:

Session.set('options', [{label: 'test1', value: 'test1', selected: true}, {label: 'test2', value: 'test2', selected: true}]);

otherwise, in newest version, is a function to remove all selected options, when form reset

**Comment by frank1340** [comment]
I'm sorry, I still do not understand.  I have a universal selectize with multiple values selected from a Meteor collection.  I want to on one click remove all selected choices.  I also want to have an event on 'add_item', as the 'change' event occurs on rendering.

**Comment by MichalW** [comment]
Can you send me a piece of code to show me how you use package?

**Comment by frank1340** [comment]
In html, for filtering a table:

`<div class="col-md-9">
                    <label>CCM Problems</label>
                    {{> universeSelectize id="ccm-problems" name="ccmProblems" options=templateNames multiple=true}}
                </div>
`
In js, trying to change the list of items needed to match:

`
    'change #ccm-problems':function(e,t) {
        var templateIdArray = $('#ccm-problems').val();
        Session.set('ccmProblemsFilterValue', templateIdArray);
        if (templateIdArray !== null) {
            t.ccmProblemFilter.set({$all:templateIdArray});
        }
        else {
            t.ccmProblemFilter.set();
        }
    }

`
templateNames:

`
    templateNames:function() {
        var templateNames = carePlanTemplates.find({}, {sort: {name: 1}}).map(function (t) {
            return {label: t.name, value: t._id._str};
        });
        return templateNames;
    }
`

**Comment by MichalW** [comment]
Could you show me the helper: `templateNames`?

**Comment by MichalW** [comment]
Please try some like this:

```
templateNames: function() {
    var templateNames = carePlanTemplates.find({}, {sort: {name: 1}}).map(
         function (t) { 
              var values = Session.get('selectedValues') || [];
              if (_.contains(values, t._id)) {
                  return {label: t.name, value: t._id._str, selected: true}; 
              }
              return {label: t.name, value: t._id._str}; 
         }
    ); 
    return templateNames;
}
```

and event like this:

```
'change #ccm-problems': function(e,t) {
    var templateIdArray = $('#ccm-problems').val();
    Session.set('ccmProblemsFilterValue', templateIdArray);
    if (templateIdArray !== null) {
        Session.set('selectedValues', $all:templateIdArray);
    } else {
        Session.set('selectedValues', []);
    }
}
```
